//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirogramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatLists
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Number { get; set; }
        public string WithNumber { get; set; }
        public string WithUser { get; set; }
    }
}
