//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirogramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequests
    {
        public long ID { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
    }
}
