//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirogramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public long ID { get; set; }
        public string Content { get; set; }
        public string FromUserID { get; set; }
        public string ToUserID { get; set; }
        public string TimeSent { get; set; }
        public Nullable<long> InReplyTo { get; set; }
        public string FromNumber { get; set; }
        public string ToNumber { get; set; }
    }
}
