//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirogramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Phones { get; set; }
        public string Friends { get; set; }
        public string LastOnline { get; set; }
    }
}
